language: python
env:
- TOXENV=py27
- TOXENV=py33
go:
- 1.7.5

install: pip install tox
script: tox
services:
  - redis-server
  - memcached
  - mongodb
before_script:
  - source ./.travis/start_minio.sh
  - psql -c 'create database simplekv_test;' -U postgres
  - mysql -e 'create database simplekv_test;'
